name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main  # 只有当 main 分支有更新时，才会触发部署

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Node.js version
        id: detect-node
        run: echo "NODE_VERSION=$(node -p 'require("./package.json").engines.node || "18"')" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}  # 自动匹配本地 Node.js 版本
          cache: 'npm'  # 缓存依赖，提高速度

      - name: Install dependencies
        run: npm install

      - name: Build Svelte app
        run: npm run build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: build  # ⚠️ SvelteKit 默认是 build/，如果你用的是 Vite Svelte，请改成 dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
