name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write  # ✅ 让 `deploy-pages@v2` 访问 artifact

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build SvelteKit App
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"  # ✅ 确保 `BASE_PATH` 适用于 GitHub Pages
        run: npm run build

      - name: Debug: List build directory
        run: ls -lah build/

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/  # ✅ 确保上传 `build/` 目录
          name: github-pages  # ✅ 确保 artifact 名称正确

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # ✅ 确保 `deploy-pages@v2` 读取正确的 artifact