name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write  # ✅ 确保 `deploy-pages@v2` 访问 artifact

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build SvelteKit App
        run: |
          set -e
          BASE_PATH="/${{ github.event.repository.name }}" npm run build

      - name: Debug build directory
        run: |
          echo "Checking build directory..."
          ls -lah build/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/  # ✅ 确保上传 `build/` 目录
          name: github-pages  # ✅ 确保 artifact 名称正确

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # ✅ 确保 `deploy-pages@v2` 读取正确的 artifact